name: Test Transition Issue

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'dev'

  issue_comment:
    types: [created]

  pull_request_review:
    types: [submitted]

  pull_request_review_comment:
    types: [created]

jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Task to Waiting Review
        if: ${{ "!github.event.pull_request.draft" }}
        run: echo "TRANSITION_NAME=On Review" >> "$GITHUB_ENV"
          

      - name: Task to Code Review
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request || github.event.name == 'pull_request_review_comment'}}
        run: echo "TRANSITION_NAME=Start Review" >> "$GITHUB_ENV"
          

      - name: Task to Reviewed
        if: ${{ github.event.review.state == 'APPROVED' }}
        run: echo "TRANSITION_NAME=Reviewed" >> "$GITHUB_ENV"

      - name: Move jira task
        run: echo ${{ env.TRANSITION_NAME }}
